### ISSUE TITLE
Create Wiki page for PAB meeting minutes and plan

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/Summer2022_FermilabProjects#3]

**Comment by rtraofa** [comment]
Meeting Minutes with Flor [https://docs.google.com/document/d/1g-ym443LmJmQShUMpGd7Cbd_oyRT86hjkkPXDbfDtrs/edit?usp=drivesdk](url)

**Comment by rtraofa** [comment]
- Preparation time for Blanche: 2-3 days
- Want the set up to be as low as possible inside Blanche.  There needs to be some gas space under the lid. 
- Needs all the stuffs have same thermo coefficients so none of the bolts come loose
- Cables/wires: no plastic; No pvc 
- Check the ratings can be used for cold
- Database for materials. Email Flor to get the link. Check with bigger experiments(Proto Dune/any DUNE test stands) to ask what materials were used. 
- TSW: Add addendum option to edit after submission; Check with Flor to ensure it is submitted; Might not have been submitted the first time we tried 
- Clarify with Joseph to ask if we need specific electrical or technical support
- Have to Cc Flor to approve the purchases and can approve upto $2500. 
- Prep: to loan equipments
- Blanche + other documents/drawings: ask Flor
- ORC: before testing anything you need to have it. Don't request before you are completely ready to test. For electronics, you need diagrams. 
- After bench setup: Ask Flor for the black oscilloscope in the closet
- Basic Cryosafe Training + Accessing building (needs building training)
- No 2 person rule
- Techs leave at 3:30 pm and come at 7:00 am. 
- Make a wikipage in github for the minutes
- Action item: 
- Email to Flor: list of things to ask her for. Building access for Raofa(her card doesn't have a chip), email list to get on, meetings to attend, ask for the Blanche wikipage, action stuff for her email, 
- Ask Joseph for task force/code number for buying stuff and the trainings. Confirmation of what kind of engineering support is needed
- Tasks for Raofa: 
- Give Fernanda Raofa's Github name
- F and R needs to start a wikipage for adding meeting minutes 
-

**Comment by FernandaPsihas** [comment]
Perfect, @SquishyRaofa ! Next step is to organize by topic and add to this wiki page I created https://github.com/FernandaPsihas/Summer2022_FermilabProjects/wiki/Tiny-TPC-Setup

**Comment by FernandaPsihas** [comment]
I'll add my notes here also
