### ISSUE TITLE
List items to email Flor about 

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/Summer2022_FermilabProjects#4]
Create list on this issue. Close the issue when email is sent.

**Comment by rtraofa** [comment]
- List of things to ask her for
- Building access for Raofa(her card doesn't have a chip)
- Email list to get on
- Meetings to attend
- Ask for the Blanche wikipage/drawings
- Action stuff for her email
- Trainings for Raofa and Fernanda
- Link for prep (to borrow equipments)

**Comment by jzennamo** [comment]
Here is a list of drawings for Blanche:
https://lartpc-docdb.fnal.gov/cgi-bin/private/ShowDocument?docid=1331
(sign in details are lartpc/argon!)

**Comment by FernandaPsihas** [comment]
Ok, I emailed Flor and added this link to the wiki under Resources. Will close this issue now.
