### ISSUE TITLE
Sumbit new TSW

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/Summer2022_FermilabProjects#6]

**Comment by rtraofa** [comment]
Link : https://docs.google.com/spreadsheets/d/1cwsKZ-bpwSwFX57QFOlUfT7zkRVBh_hj/edit?usp=sharing&ouid=108844884968933331309&rtpof=true&sd=true

**Comment by FernandaPsihas** [comment]
We are missing the specs for the power supply we need. @SquishyRaofa this is the documentation that we have, some of it is for  a board with 10x10 chips (we have a 3x3) but it is translatable. Could you go through it and see if the specs for the power supply we need are in there? https://drive.google.com/drive/folders/11MLALCLddn0OC8BdfMGsJi6GAmBltERf?usp=sharing

**Comment by FernandaPsihas** [comment]
I will ask Andy in parallel
