### ISSUE TITLE
Create google sheets list of items needed for setup

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/Summer2022_FermilabProjects#7]

**Comment by FernandaPsihas** [comment]
We can start categorizing things as need to purchase/available at PAB/need to borrow from (what is that place called?) etc.

**Comment by FernandaPsihas** [comment]
Oh and we will want to add the google sheets link to the wiki page

**Comment by rtraofa** [comment]
- Oscilloscope (Flor has it)
-  Cables 
-  A power supply for the bench tests, 
- A volt meter 
- A set of gloves that reduce static
- Safety Glasses (Might not need it)
- Anti-static bracelet
- Insulating Tape 
- Wires
- Surge Protector 
- Wire Cutter

**Comment by FernandaPsihas** [comment]
I added a google sheets doc to the Google drive folder. Can you confirm that you have permissions to edit it please @SquishyRaofa, @jzennamo ? Once we know we can all access it then we can close this issue and start adding stuff there.
