### ISSUE TITLE
Add basic cryo safety training to Raofa's and Fernanda's ITNA

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/Summer2022_FermilabProjects#8]
Flor asked us to take this. She thinks this will be good to have in general but also we will need it if any dunk tests are necessary.

**Comment by jzennamo** [comment]
hm. I don't seem to be able to add it

**Comment by jzennamo** [comment]
Instead we'll try to do it like this: 

Does this link work?

https://www-esh.fnal.gov/pls/cert/schedule.show_course_details?this_course_code=FN000115&this_instr_type=CR&this_fermi_id=45429N

if not, sign in to the VPN and go here https://www-esh.fnal.gov/pls/cert/course_list.rpt and search for “[FN000115/CR] Cryogenic Safety (General)” you should be able to click the like and it will bring you to the course and the test

**Comment by rtraofa** [comment]
> Instead we'll try to do it like this:
> 
> Does this link work?
> 
> https://www-esh.fnal.gov/pls/cert/schedule.show_course_details?this_course_code=FN000115&this_instr_type=CR&this_fermi_id=45429N
> 
> if not, sign in to the VPN and go here https://www-esh.fnal.gov/pls/cert/course_list.rpt and search for “[FN000115/CR] Cryogenic Safety (General)” you should be able to click the like and it will bring you to the course and the test

Completed!
